spring:
  ai:
    dashscope:
      api-key: 	sk-cf87efd6e87a4e49bf013f4256a550e6
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
          model: gemma3:1b

api-key-volengine: f40aed42-318b-4ebf-8fbb-e0e735515a0d