spring:
  ai:
    dashscope:
      api-key: sk-488ba1054a114c98bbdc6b594a5cef5b
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
          model: gemma3:1b

